postgres:
  host: localhost
  post: 5432
  dbname: test-faucet
  user: postgres
  password: admino0o0oo0
  sslmode: disable
server: 0.0.0.0:3434 #server host:port
total: 100 #daily upper coin limit
amount: 10 #coin amount
coin: fermion #coin denom
iris: 81A2BB25F7CB65ADA740FF7733148AF904BA1BB9 #gaia account address
name: faucet #gaia account name
password:   #gaia account password
client: http://47.104.155.125:8999 #gaia client
